### This file acts as the global config across the website.
### Any variables in this file can be accessed in other files using
###    `{{ site.variable }}`


######################
# Site configuration #
######################
# This title will display across the website
title: "Civil Service LGBT+ Network"
# This description is predominantly for Search Engine Optimisation
description: "The Civil Service LGBT+ Network helps to create a more diverse, inclusive and equal place to work for civil servants who are lesbian, gay, bisexual and trans, or who have another minority sexual orientation, gender identity or expression or sex characteristics."
# Instead of "author", have the organisation name as the default
author: "Civil Service LGBT+ Network"
organisation: "Civil Service LGBT+ Network"
email: "info@civilservice.lgbt"

baseurl: "/design-system" # the subpath of your site, e.g. /blog
url: "https://www.civilservice.lgbt"

#########################
# Social media accounts #
#########################
social-media-accounts:
  - account: "Facebook"
    url: "//facebook.com/civilservicelgbt"
    display-text: "Like us on Facebook"
    alt-text: "Visit our Facebook profile page"
    handle: "civilservicelgbt" # Automatically pre-pends http://facebook.com/
    hidden: false
  - account: "Twitter"
    url: "//twitter.com/cslgbt" # Twitter handle i.e. joebloggs
    display-text: "Follow us on Twitter"
    alt-text: "Visit our Twitter profile page"
    handle: "cslgbt" # Twitter handle i.e. joebloggs
    hidden: false
  - account: "Flickr"
    url:  "//www.flickr.com/photos/civilservicelgbt/"
    display-text: "Find us on Flickr"
    alt-text: "Visit our Flickr profile page"
    handle:  "civilservicelgbt"
    hidden: false
  - account: "Instagram"
    url:  "//www.instagram.com/civilservicelgbt"
    display-text: "Follow us on Instagram"
    alt-text: "Visit our Instagram profile page"
    handle:  "civilservicelgbt"
    hidden: false
  - account: "Youtube"
    url: "//youtube.com/"
    display-text: "Subscribe to us on Youtube"
    alt-text: "Visit our Youtube profile page"
    handle: ""
    hidden: true

###################
# Header settings #
###################
header-menu--links--hidden: false
# Header menu links
header-menu--links:
  - display-text: "Home"
    alt-text: "Visit the home page"
    url: "https://www.civilservice.lgbt/"
    hidden: true
  - display-text: "News"
    alt-text: "Visit the News page"
    url: "https://www.civilservice.lgbt/news"
    hidden: false
  - display-text: "Events"
    alt-text: "Visit the Events page"
    url: "https://www.civilservice.lgbt/events"
    hidden: false
  - display-text: "Topics"
    alt-text: "Visit the Topics page"
    url: "https://www.civilservice.lgbt/topics"
    hidden: false
  - display-text: "Publications"
    alt-text: "Visit the Publications page"
    url: "https://www.civilservice.lgbt/publications"
    hidden: false
  - display-text: "Consultations"
    alt-text: "Visit the Consultations page"
    url: "https://www.civilservice.lgbt/consultations"
    hidden: false
  - display-text: "Networks"
    alt-text: "Visit the Networks page"
    url: "https://www.civilservice.lgbt/networks"
    hidden: false
  - display-text: "Our team"
    alt-text: "See who we are"
    url: "https://www.civilservice.lgbt/team"
    hidden: false
  - display-text: "About"
    alt-text: "Learn more about us"
    url: "https://www.civilservice.lgbt/about"
    hidden: false
  - display-text: "Join us"
    alt-text: "Visit the membership registration page"
    url: "https://www.civilservice.lgbt/join-us"
    hidden: false

###################
# Footer settings #
###################
# This text will be displayed at the bottom of the website.
footer--production-notice: "Website created by <a href='//www.johnpe.art' title='Visit John Peart’s website (Opens in new window)' target='_blank' rel='noopener noreferrer'>John Peart</a>."
footer--copyright-notice: "All content is released under the <a href='https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/' title='Read more about the Open Government License. (Opens in new window)' target='_blank'>Open Government License</a> unless otherwise stated. Please attribute our work."

# Footer menu links
footer-menu--links:
  - display-text: "Design system"
    alt-text: "Visit the design system"
    url: "https://www.civilservice.lgbt/design-system"
    hidden: false
  - display-text: "Volunteer manuals"
    alt-text: "Read the volunteer manuals"
    url: "https://www.civilservice.lgbt/manuals"
    hidden: false

###############
# Asset paths #
###############
# General paths
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"

# Favicons and social graph
social-media-image: "/assets/images/site/social-media.png"
favicon: "/favicon.ico"
favicon-svg: "/assets/images/site/favicon.svg"
favicon-pinned-svg: "/assets/images/site/favicon-pinned-svg.svg"
favicon-large-png: "/assets/images/site/favicon-large-png.png"
theme-colour: "#e6007e"



##################################
# Analytics and domain ownership #
##################################
# Google settings
google-site-verification: "RA-YBjxyRYVSuSFAYLKkufs6gjme6kMcihoB2KgKrTA"

##############
# Newsletter #
##############
# Mailchimp
unsubscribe-form: "https://us17.admin.mailchimp.com/lists/designer/?id=118945"

###############
# Collections #
###############
#This is the default permalink for the "_posts" folder.
permalink: /:year/:month/:day/:title:output_ext

collections:
    design-system:
        output: true
        permalink: /:path/
        defaults:
            values:
                layout: design-system

##################
# Build settings #
##################
remote_theme: civilservicelgbt/magenta
permalink: pretty
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass

plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/